export const USER = {
  REGISTER_USER: "REGISTER_USER",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
  LOGOUT_USER: "LOGOUT_USER",
  FETCH_CURRENT_USER: "FETCH_CURRENT_USER",
};

export const BOARDS = {
  GET_ALL_BOARDS: "GET_ALL_BOARDS",
  GET_ALL_BOARDS_SUCCESS: "GET_ALL_BOARDS_SUCCESS",
  GET_ALL_BOARDS_ERROR: "GET_ALL_BOARDS_ERROR",
  GET_ONE_BOARD: "GET_ONE_BOARD",
  GET_ONE_BOARD_SUCCESS: "GET_ONE_BOARD_SUCCESS",
};
